openapi: 3.0.0
info: # info about the project
  title: E-Commerce API
  description: return products, create, update and delete products
  version: 1.0.0

servers:
  # server url
  - url: "http://localhost:1000/" 
    description: for local host server

# for auth
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

# routes
paths:
  /:
    get:
    # grouping the paths
      tags:
        - Greetings
      summary: return a greeting message
      responses:
        200:
          description: Success, OK
          content:
            application/json:
              schema:
                type: string
                example: "greetingString"
        400:
          description: Bad request
        500:
          description: Internal Server Error
  
  /products:
    get:
    # grouping the paths
      tags:
        - Product List
      summary: return list of all the products
      responses:
        200:
          description: Success, OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    quantity:
                      type: number
        400:
          description: Bad request
        500:
          description: Internal Server Error
  
  /products/create:
    # request type is post
    post:
      tags:
        - Create
      summary: add a new product to the database
      # type of data taken
      consumes:
        - application/json
      # type of output produced
      produces:
        - application/json
      # params passed to add new course
      requestBody:
        # all values are required
        required: true
        # content 
        content:
          application/json:
            schema:
              # takes an object
              type: object
              properties:
                name:
                  type: string
                quantity:
                  type: number
      responses:
        200:
        # return the entered object
          description: Success, OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                  name:
                    type: string
                  quantity:
                    type: number
        400:
          description: Bad request
        500:
          description: Internal Server Error
    